version: '3.7'

services:

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/flask_app
    ports:
      - target: 5000
        published: 5000
    # environment:
    #   foo: bar
    env_file:
      - devops/common.env

  # redis:
  #   image: redis:6.0.5-alpine
  #   expose:
  #     - 6379
  #   ports:
  #     - target: 6379
  #       published: 6379
    